test setup

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,17 +8,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      # - uses: ./.github/actions/action-setup
+      #   id: action-setup
+      #   with:
+      #     version: "8.0.408"
       - run: |
           pwd
           ls -la $HOME
           echo $PATH
-          command -v dotnet || echo 'dotnet not found'
-      - uses: ./.github/actions/action-setup
-        id: action-setup
-        with:
-          version: "8.0.408"
-      - run: |
-          pwd
-          ls -la $HOME
-          echo $PATH
-          command -v dotnet || echo 'dotnet not found'
+          dotnet --version || echo 'dotnet not found'
